/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    InfoBlock: typeof import('./src/components/InfoBlock/index.vue')['default']
    LeftSubOptions: typeof import('./src/components/LeftSubOptions/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubOptionsItemsCard: typeof import('./src/components/SubOptionsItemsCard/index.vue')['default']
    TextMessage: typeof import('./src/components/MessageBubble/TextMessage/index.vue')['default']
  }
}
